apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 170643462794.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 170643462794.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: f85a6cfd
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
